### ISSUE TITLE
Please attach the name of paper

### ISSUE THREAD

**Issue by juhonkang** [vygr/Python-PCB#2]
Hi, could you please give the community the paper your router is based on and how to customize it?
Thanks!

**Comment by juhonkang** [comment]
Hi, could you please give the community the paper your router is based on and how to customize it?
Thansk!

**Comment by vygr** [comment]
Hi. It’s not based on a paper.

One day I became interested in the routing problem and decided to have a go. This router is what I came up with.

The C++ version, available in the project list. It’s probably the most advanced version. But they’re all based on the same idea.

Chris 

—————-
Chris Hinsley

**Comment by juhonkang** [comment]
Ok, thanks!
